FROM node:20-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm
COPY ./bun.lock  ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json   ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN pnpm install

EXPOSE 4002

CMD ["pnpm","run","start:frontend"]